deploy_test:
  stage: deploy
  script:
    - echo "Deploy to test server"
  environment:
    name: staging/$CI_COMMIT_REF_NAME
    url: $CI_ENVIRONMENT_SLUG
  only:
  - release

deploy_release:
  stage: deploy
  image: centos
  environment:
    name: deploying/$CI_COMMIT_REF_NAME
    url: $CI_ENVIRONMENT_SLUG

  before_script:
    - cd /$BUILD_LINK
    - yum install which -y
    - "which ssh-agent || ( yum update -y && yum install openssh-server openssh-clients -y )"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/gitlab
    - chmod 600 ~/.ssh/gitlab
    - eval "$(ssh-agent -s)"
    - ssh-add  ~/.ssh/gitlab
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    - yum install rsync -y -qq
    - yum install curl -y -qq

  script:
    - cd /$BUILD_LINK/
    - ssh -i ~/.ssh/gitlab -o StrictHostKeyChecking=no $USER_SERVER@$IP_SERVER -p $PORT_SERVER  -T "cd /$URL_SERVER && git stash"
    - ssh -i ~/.ssh/gitlab -o StrictHostKeyChecking=no $USER_SERVER@$IP_SERVER -p $PORT_SERVER  -T "cd /$URL_SERVER && git pull"
    - ssh -i ~/.ssh/gitlab -o StrictHostKeyChecking=no $USER_SERVER@$IP_SERVER -p $PORT_SERVER  -T "cd /$URL_SERVER && cp .env.production .env"
    - ssh -i ~/.ssh/gitlab -o StrictHostKeyChecking=no $USER_SERVER@$IP_SERVER -p $PORT_SERVER  -T "cd /$URL_SERVER && yarn install"
    - rsync -avz --progress -a -e "ssh -p $PORT_SERVER" /$BUILD_LINK/build $USER_SERVER@$IP_SERVER:/$URL_SERVER

    - echo "Copy file to Deloy Success"

  only:
    - release
